---
apiVersion: v1
kind: Namespace
metadata:
  name: apj-front
---
apiVersion: v1
kind: Namespace
metadata:
  name: apj-back
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-staging-anonymous-sets
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-anonymizer
