---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: gcp-staging-west1
spec:
  selector:
    matchLabels:
      region: europe-west1
      environnement: staging
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: gcp-staging-west1d
spec:
  selector:
    matchLabels:
      datacenter: europe-west1-d
      environnement: staging