---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: api-ingress-nodeport
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
