---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
  annotations:
    configmanagement.gke.io/managed: disabled
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld

