#&rescue_account_name db-ops
#&rescue_ns_name mongodb
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: metallikaas-prod-nd1
  name: db-ops
  namespace: mongodb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: gcp-staging-west1
  name: db-ops
  namespace: mongodb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rescue-admin-access
  namespace: mongodb
subjects:
- kind: ServiceAccount
  name: db-ops
  namespace: mongodb
roleRef:
  kind: Role
  name: mongodb-operator
  apiGroup: rbac.authorization.k8s.io
